import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
  keywords: ["Contact page"]
};
export default function ContactPage() {
  return (
    <>
      <span className="text-3xl">Hola Contact</span>
    </>
  )
}
