import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pricing Page",
  description: "Generated by create next app",
  keywords: ["Pricing page"]
};
export default function PricingPage() {
  return (
    <>
      <span className="text-3xl">Hola Pricing</span>
    </>
  )
}
