import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "home page",
  description: "Generated by create next app",
  keywords: ["about page"]
};
export default function AboutPage() {
  return (
    <>
      <span className="text-3xl">Hola About</span>
    </>
  )
}
